#!/bin/sh

# display Hugging Face Spaces log stream (Server-Sent Events)

. .env
curl -sNH "Authorization: Bearer $HF_TOKEN" \
        https://huggingface.co/api/spaces/jeremy-dolan/digital-twin/logs/build \
    | sed -un 's/^data: //p' \
    | grep --line-buffered . \
    | jq --unbuffered -r '
        "\(
          .timestamp
          | sub("\\.[0-9]+Z$"; "Z")
          | fromdateiso8601
          | strflocaltime("%Y-%m-%d %H:%M:%S")
        ): \(.data)"
    '
